version: "3.7"

services:
  storefront:
    container_name: storefront
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
      - "/app/coverage"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
