version: "3.2"
services:
  storefront:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - "../:/app"
      - "../app/node_modules"
    environment:
      - PORT=8123
  cypress:
    image: "cypress/included:4.0.1"
    depends_on:
      - storefront
    environment:
      - CYPRESS_baseUrl=http://storefront:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e
