#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "tsx$")
if [[ "$STAGED_FILES" = "" ]];
then
    exit 0
fi

echo something here $STAGED_FILES

PASS=true

npm run test:staged $STAGED_FILES
if [[ "$?" == 0 ]]; then
    echo "\t\033[32mJest Tests Passed\033[0m"
else
    echo "what is this $?"
    echo "\t\033[41mJest Tests Failed\033[0m"
    PASS=false
fi
