#!/bin/bash

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "tsx$")
if [[ "$STAGED_FILES" = "" ]];
then
    exit 2
fi

echo something here $STAGED_FILES


docker exec storefront /bin/bash -c jest --bail --findRelatedTests ${STAGED_FILES}
if [[ "$?" == 0 ]]; then
    echo "\t\033[32mJest Tests Passed\033[0m"
else
    echo "\t\033[41mJest Tests Failed\033[0m"
fi
