#!/bin/bash

rm ./LighthouseOutput/*

GT=$(git log -1 --pretty=format:'%H')

lighthouse http://localhost:3000 --output 'json' 'html' --output-path ./LighthouseOutput/$(date +%F+%S)."$GT"
# lighthouse http://localhost:3000 --view --output 'json' 'html' --output-path ./LighthouseOutput/$(date +%F+%S)."$GT"

docker exec -it storefront /bin/bash -c "node reportReader.js" 

git add .